apiVersion: v1
kind: Secret
metadata:
  name: kubeconfig-kubermatic
  namespace: kubermatic
type: Opaque
data:
  kubeconfig: <base64 encoded kubeconfig>
---
apiVersion: kubermatic.k8c.io/v1
kind: Seed
metadata:
  # The Seed *must* be named "kubermatic".
  name: kubermatic
  namespace: kubermatic
spec:
  # These two fields are only informational.
  country: DE
  location: Hamburg

  # List of datacenters where this seed cluster is allowed to create clusters in; see below for examples.
  datacenters:
    aws-eu-central-1a:
      country: DE
      location: EU (Frankfurt)
      spec:
        aws:
          region: eu-central-1

  # etcd backup and restore configuration. See below for how to configure this section, depending
  # on the storage backend you chose. Omit this field if you do not wish to configure etcd backups.
  etcdBackupRestore: {}

  exposeStrategy: Tunneling

  # Reference to the kubeconfig to use when connecting to this seed cluster.
  kubeconfig:
    name: kubeconfig-kubermatic
    namespace: kubermatic
